--Catalogo de areas de interes
INSERT INTO AREA_INTERES(AREA_INTERES_ID, NOMBRE, CLAVE) VALUES(1, 'BASES DE DATOS', 'BD');
INSERT INTO AREA_INTERES(AREA_INTERES_ID, NOMBRE, CLAVE) VALUES(2, 'PROGRAMACION', 'PR');
INSERT INTO AREA_INTERES(AREA_INTERES_ID, NOMBRE, CLAVE) VALUES(3, 'ANALISIS DE SISTEMAS DE SOFTWARE', 'AN');
INSERT INTO AREA_INTERES(AREA_INTERES_ID, NOMBRE, CLAVE) VALUES(4, 'HARDWARE', 'HW');

--Catalogo de status articulo
INSERT INTO STATUS_ARTICULO(STATUS_ARTICULO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(1, 'RE', 'RECIBIDO', 1);
INSERT INTO STATUS_ARTICULO(STATUS_ARTICULO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(2, 'RV', 'REVISADO', 1);
INSERT INTO STATUS_ARTICULO(STATUS_ARTICULO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(3, 'RC', 'RECHAZADO', 1);
INSERT INTO STATUS_ARTICULO(STATUS_ARTICULO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(4, 'PR', 'PROGRAMADO', 1);
INSERT INTO STATUS_ARTICULO(STATUS_ARTICULO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(5, 'PB', 'PUBLICADO', 1);
