CREATE UNIQUE INDEX articulo_id_idx ON ARTICULO(ARTICULO_ID);
CREATE UNIQUE INDEX empleado_id_idx ON EMPLEADO(EMPLEADO_ID);
CREATE UNIQUE INDEX publicacion_id_idx ON PUBLICACION(PUBLICACION_ID);
CREATE UNIQUE INDEX suscriptor_id_idx ON SUSCRIPTOR(SUSCRIPTOR_ID);
CREATE UNIQUE INDEX escritor_id_idx ON ESCRITOR(ESCRITOR_ID);
