CREATE USER GAOR_PROY_ADMIN IDENTIFIED BY ADMINISTRADOR QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO GAOR_PROY_ADMIN;
GRANT CREATE TABLE TO GAOR_PROY_ADMIN;
GRANT CREATE VIEW TO GAOR_PROY_ADMIN;
--GRANT CREATE INDEX TO GAOR_PROY_ADMIN;
GRANT CREATE SEQUENCE TO GAOR_PROY_ADMIN;
GRANT CREATE SYNONYM TO GAOR_PROY_ADMIN;
GRANT CREATE PROCEDURE TO GAOR_PROY_ADMIN;

CREATE USER GAOR_PROY_USER IDENTIFIED BY USUARIO;
GRANT CREATE SESSION TO GAOR_PROY_ADMIN;
SELECT 'GRANT READ ON GAOR_PROY_ADMIN.' ||TABLE_NAME|| ' TO GAOR_PROY_USER; '
FROM DBA_TABLES T
WHERE T.OWNER = 'GAOR_PROY_ADMIN';
