CREATE OR REPLACE VIEW V_EMPLEADO_REVISOR(
EMPLEADO_ID, NOMBRE, APELLIDIO_PATERNO, APELLIDO_MATERNO, EMAIL, FECHA_INGRESO,
NUM_CONTRATO, FECHA_FIN)
AS
SELECT E.EMPLEADO_ID, E.NOMBRE, E.APELLIDO_PATERNO, E.APELLIDO_MATERNO, E.EMAIL, E.FECHA_INGRESO,
R.CONTRATO, R.FECHA_FIN
FROM EMPLEADO E
JOIN EMPLEADO_REVISOR R
ON E.EMPLEADO_ID = R.EMPLEADO_ID;

CREATE OR REPLACE VIEW V_EMPLEADO_EDITOR(
EMPLEADO_ID, NOMBRE, APELLIDIO_PATERNO, APELLIDO_MATERNO, EMAIL, FECHA_INGRESO,
CEDULA, NOMBRE_GRADO)
AS
SELECT E.EMPLEADO_ID, E.NOMBRE, E.APELLIDO_PATERNO, E.APELLIDO_MATERNO, E.EMAIL, E.FECHA_INGRESO,
EE.CEDULA, EE.NOMBRE_GRADO
FROM EMPLEADO E
JOIN EMPLEADO_EDITOR EE
ON E.EMPLEADO_ID = EE.EMPLEADO_ID;

CREATE OR REPLACE VIEW V_SUSCRIPTOR(
SUSCRIPTOR_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, FECHA_INICIO_SUSCRIPCION, FECHA_FIN_SUSCRIPCION,
CALLE, NUMERO, COLONIA, CP, DELE_MUNI, ESTADO)
AS
SELECT S.SUSCRIPTOR_ID, S.NOMBRE, S.APELLIDO_PATERNO, S.APELLIDO_MATERNO, S.EMAIL, S.FECHA_INICIO_SUSCRIPCION, S.FECHA_FIN_SUSCRIPCION,
D.CALLE, D.NUMERO, D.COLONIA, D.CP, D.DELEGACION_MUN, D.ESTADO
FROM SUSCRIPTOR S
JOIN DIRECCION D
ON S.SUSCRIPTOR_ID = D.SUSCRIPTOR_ID;
